# Data Analysis with Python

This project demonstrates exploratory data analysis (EDA), data cleaning, and statistical insights using Pandas and Matplotlib.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Create Dataset with Missing Values**

In [2]:
data = {
    "Age": [21, 22, np.nan, 24, 23],
    "Marks": [85, 90, 78, np.nan, 88],
    "Study_Hours": [2, 3, 4, 5, np.nan]
}

df = pd.DataFrame(data)
df

    Age  Marks  Study_Hours
0  21.0   85.0          2.0
1  22.0   90.0          3.0
2   NaN   78.0          4.0
3  24.0    NaN          5.0
4  23.0   88.0          NaN

**Handle Missing Values**

In [3]:
df.fillna(df.mean(numeric_only=True), inplace=True)
df

    Age  Marks  Study_Hours
0  21.0  85.00          2.0
1  22.0  90.00          3.0
2  22.5  78.00          4.0
3  24.0  85.25          5.0
4  23.0  88.00          3.5

**Statistical Summary**

In [4]:
df.describe()

             Age      Marks  Study_Hours
count   5.000000   5.000000     5.000000
mean   22.500000  85.250000     3.500000
std     1.118034   4.548351     1.118034
min    21.000000  78.000000     2.000000
25%    22.000000  85.000000     3.000000
50%    22.500000  85.250000     3.500000
75%    23.000000  88.000000     4.000000
max    24.000000  90.000000     5.000000

In [5]:
df.corr()

                  Age     Marks  Study_Hours
Age          1.000000 -0.030726     0.950000
Marks       -0.030726  1.000000    -0.276537
Study_Hours  0.950000 -0.276537     1.000000